apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: default
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST1
          valueFrom:
            secretKeyRef:
              name: wordpress-db-secret
              key: WORDPRESS_DB_HOST1
        - name: WORDPRESS_DB_USER1
          valueFrom:
            secretKeyRef:
              name: wordpress-db-secret
              key: WORDPRESS_DB_USER1
        - name: WORDPRESS_DB_PASSWORD1
          valueFrom:
            secretKeyRef:
              name: wordpress-db-secret
              key: WORDPRESS_DB_PASSWORD1
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: wordpress-db-secret
              key: WORDPRESS_DB_NAME
